---
name: Lint

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint-python:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Lint python scripts
      id: run
      run: |
        pylint **/*.py
